title: "Joe Choo-Choy"

assets: /assets/
resume: /assets/cv.pdf

# photos
photo_1: /assets/photo_1.jpeg
photo_2: /assets/photo_2.jpeg
photo_3: /assets/photo_3.jpeg
photo_4: /assets/photo_4.jpeg
photo_5: /assets/photo_5.jpeg
photo_6: /assets/photo_6.jpeg
photo_7: /assets/photo_7.jpeg

# permalinks, alphabetical
about_permalink: /about/
blog_permalink: /blog/
book_notes_permalink: /book_notes/
cog_permalink: /cog/
cognitive_science_notes_permalink: /cognitive_science_notes/
formal_science_notes_permalink: /formal_science_notes/
lists_permalink: /lists/
quotations_permalink: /quotations/
recent_reading_permalink: /recent_reading/
reel_permalink: /reel/
resources_permalink: /resources/
short_lived_permalink: /short_lived/
tidbytes_permalink: /tidbytes/
tracking_permalink: /tracking/

email: joechoochoy@gmail.com
google_scholar: https://scholar.google.co.uk/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jchooch.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  joechoochoy
github_username:   jchooch
linkedin_username: joe-choo-choy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:title  #replaces folder structure /YY/mm/dd/categories/title by only /title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
