title: "Joe Choo-Choy"
email: joechoochoy@gmail.com
assets: /assets/
resume: /assets/cv.pdf
photo: /assets/photo.jpeg
resources_permalink: /resources/
tidbytes_permalink: /tidbytes/
lists_permalink: /lists/
cog_permalink: /cog/
recent_reading_permalink: /recent_reading/
google_scholar: https://www.google.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jchooch.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  joechoochoy
github_username:   jchooch
linkedin_username: joe-choo-choy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:title  #replaces folder structure /YY/mm/dd/categories/title by only /title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
